### ISSUE TITLE
Unable to search for subreddits

### ISSUE THREAD

**Issue by noesterle** [oppiliappan/lurker#16]
## Problem
When I try searching for a subreddit such as `Android`, the application crashes.

## Version
I am using the latest image, built 10 hours ago as of the time of this writing.
Image Hash: `Digest: sha256:c97e39d22514d1c4446b418a0afc23186b7f3e24ce28be59bebf766c0dc612bb`

## Setup
I am using the following Docker Compose:
```yml
services:
  lurker:
    image: ghcr.io/oppiliappan/lurker
    container_name: lurker
    restart: unless-stopped
    volumes:
      - /data/docker/lurker/data:/data
    ports:
      - 3030:3000
    networks:
      - lurker_net

networks:
  lurker_net:
    name: lurker_net
```

## Steps to reproduce:
1. `docker compose up -d`
2. Navigate to Lurker in the Web Browser, in this case `0.0.0.0:3030`.
3. On the main page, click the `search` link.
4. In the "Search Subreddits" field, enter "Android" and click enter.

## Results:
I am given an Unable To Connect Page.

Using `docker compose logs lurker` I am shown the following:
```
lurker  | started on {
lurker  |   address: "0.0.0.0",
lurker  |   family: "IPv4",
lurker  |   port: 3000,
lurker  | }
lurker  | 115 | // GET /sub-search
lurker  | 116 | router.get("/sub-search", authenticateToken, async (req, res) => {
lurker  | 117 | 	if (!req.query || !req.query.q) {
lurker  | 118 | 		res.render("sub-search", { user: req.user });
lurker  | 119 | 	} else {
lurker  | 120 | 		const { items, after } = await G.searchSubreddits(q);
lurker  |                                                            ^
lurker  | ReferenceError: Can't find variable: q
lurker  |       at /home/bun/app/src/routes/index.js:120:54
lurker  |       at /home/bun/app/src/routes/index.js:116:53
lurker  |       at handle (/root/.bun/install/cache/express@4.21.2@@@1/lib/router/layer.js:95:5)
lurker  |       at next (/root/.bun/install/cache/express@4.21.2@@@1/lib/router/route.js:149:13)
lurker  |       at authenticateToken (/home/bun/app/src/auth.js:22:3)
lurker  |       at handle (/root/.bun/install/cache/express@4.21.2@@@1/lib/router/layer.js:95:5)
lurker  |       at next (/root/.bun/install/cache/express@4.21.2@@@1/lib/router/route.js:149:13)
lurker  |       at dispatch (/root/.bun/install/cache/express@4.21.2@@@1/lib/router/route.js:119:3)
lurker  |       at handle (/root/.bun/install/cache/express@4.21.2@@@1/lib/router/layer.js:95:5)
lurker  |       at /root/.bun/install/cache/express@4.21.2@@@1/lib/router/index.js:284:15
lurker  |       at next (/root/.bun/install/cache/express@4.21.2@@@1/lib/router/index.js:280:10)
lurker  |       at handle (/root/.bun/install/cache/express@4.21.2@@@1/lib/router/index.js:175:3)
lurker  |       at router (/root/.bun/install/cache/express@4.21.2@@@1/lib/router/index.js:47:12)
lurker  |       at handle (/root/.bun/install/cache/express@4.21.2@@@1/lib/router/layer.js:95:5)
lurker  |       at trim_prefix (/root/.bun/install/cache/express@4.21.2@@@1/lib/router/index.js:328:13)
lurker  |       at /root/.bun/install/cache/express@4.21.2@@@1/lib/router/index.js:286:9
lurker  |       at next (/root/.bun/install/cache/express@4.21.2@@@1/lib/router/index.js:280:10)
lurker  |       at /root/.bun/install/cache/express-rate-limit@7.5.0@@@1/dist/index.cjs:822:7
lurker  | 
lurker  | Bun v1.1.42 (Linux x64 baseline)
lurker exited with code 0
```

**Comment by oppiliappan** [comment]
thanks for the report, will take a look, i believe this was broken quite recently.
